# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d1d6493bd2e5412e59c98ea76c19cdf"
name = "duyanhdove"
handle = "duyanhdove-2"
application_url = "https://electro-trade-incl-conspiracy.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://electro-trade-incl-conspiracy.trycloudflare.com/auth/callback",
  "https://electro-trade-incl-conspiracy.trycloudflare.com/auth/shopify/callback",
  "https://electro-trade-incl-conspiracy.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
